// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PopFake.Data;

#nullable disable

namespace Popfake.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241022004945_avatarUrl")]
    partial class avatarUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2c5e174e-3b0e-446f-86af-483d56fd7211",
                            Name = "Player",
                            NormalizedName = "PLAYER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "80c9b350-192b-4d8f-89df-d8872ceed18f",
                            RoleId = "2c5e174e-3b0e-446f-86af-483d56fd7211"
                        },
                        new
                        {
                            UserId = "e06d6e84-822a-4485-a517-2754d05e2759",
                            RoleId = "2c5e174e-3b0e-446f-86af-483d56fd7211"
                        },
                        new
                        {
                            UserId = "ad666ca1-ff2b-4d09-a167-406b14da431f",
                            RoleId = "2c5e174e-3b0e-446f-86af-483d56fd7211"
                        },
                        new
                        {
                            UserId = "d49e3a77-6b79-4a0b-9360-d3420a5750f7",
                            RoleId = "2c5e174e-3b0e-446f-86af-483d56fd7211"
                        },
                        new
                        {
                            UserId = "3edce9ce-8819-4ec9-a68d-dd6925ad90f5",
                            RoleId = "2c5e174e-3b0e-446f-86af-483d56fd7211"
                        },
                        new
                        {
                            UserId = "0730545a-e730-42d1-ad38-af79d72e726c",
                            RoleId = "2c5e174e-3b0e-446f-86af-483d56fd7211"
                        },
                        new
                        {
                            UserId = "bcd4ac43-2f0d-40aa-a084-8b02172e598b",
                            RoleId = "2c5e174e-3b0e-446f-86af-483d56fd7211"
                        },
                        new
                        {
                            UserId = "ac7dcb36-96e4-4f2e-9187-936fae618a8b",
                            RoleId = "2c5e174e-3b0e-446f-86af-483d56fd7211"
                        },
                        new
                        {
                            UserId = "91c266f1-be7b-4f7a-86b8-d005a0fd3694",
                            RoleId = "2c5e174e-3b0e-446f-86af-483d56fd7211"
                        },
                        new
                        {
                            UserId = "dba541a5-0093-4e75-b566-4bb623bf48c0",
                            RoleId = "2c5e174e-3b0e-446f-86af-483d56fd7211"
                        },
                        new
                        {
                            UserId = "ab093ee2-c1fb-4114-9e57-0445d7e54055",
                            RoleId = "2c5e174e-3b0e-446f-86af-483d56fd7211"
                        },
                        new
                        {
                            UserId = "e087eaa7-483b-4778-bde7-461ee495b049",
                            RoleId = "2c5e174e-3b0e-446f-86af-483d56fd7211"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PopFake.Models.Atributte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Atributtes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The ability to perform tasks with precision and agility.",
                            Name = "Dexterity"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The physical power and ability to perform tasks requiring muscular effort.",
                            Name = "Strength"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The ability to learn, understand, and apply knowledge.",
                            Name = "Intelligence"
                        },
                        new
                        {
                            Id = 4,
                            Description = "The physical endurance and ability to withstand adversities.",
                            Name = "Constitution"
                        },
                        new
                        {
                            Id = 5,
                            Description = "The ability to innovate and think in an original and inventive way.",
                            Name = "Creativity"
                        });
                });

            modelBuilder.Entity("PopFake.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("BirthAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("BirthCityId")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentLocationId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Money")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BirthCityId");

                    b.HasIndex("CurrentLocationId");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 25,
                            AvatarUrl = "https://img.freepik.com/psd-gratuitas/ilustracao-3d-de-avatar-ou-perfil-humano_23-2150671122.jpg",
                            BirthAt = new DateTime(2024, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthCityId = 1,
                            CurrentLocationId = 1,
                            FirstName = "John",
                            Gender = "M",
                            LastName = "Doe",
                            Money = 0m,
                            UserId = "1"
                        },
                        new
                        {
                            Id = 2,
                            Age = 22,
                            AvatarUrl = "https://img.freepik.com/psd-gratuitas/ilustracao-3d-de-avatar-ou-perfil-humano_23-2150671122.jpg",
                            BirthAt = new DateTime(2024, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthCityId = 1,
                            CurrentLocationId = 1,
                            FirstName = "Jane",
                            Gender = "F",
                            LastName = "Doe",
                            Money = 0m,
                            UserId = "1"
                        },
                        new
                        {
                            Id = 3,
                            Age = 30,
                            AvatarUrl = "https://img.freepik.com/psd-gratuitas/ilustracao-3d-de-avatar-ou-perfil-humano_23-2150671122.jpg",
                            BirthAt = new DateTime(2024, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthCityId = 1,
                            CurrentLocationId = 1,
                            FirstName = "Bob",
                            Gender = "M",
                            LastName = "Smith",
                            Money = 0m,
                            UserId = "1"
                        },
                        new
                        {
                            Id = 4,
                            Age = 28,
                            AvatarUrl = "https://img.freepik.com/psd-gratuitas/ilustracao-3d-de-avatar-ou-perfil-humano_23-2150671122.jpg",
                            BirthAt = new DateTime(2024, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthCityId = 1,
                            CurrentLocationId = 1,
                            FirstName = "Alice",
                            Gender = "F",
                            LastName = "Johnson",
                            Money = 0m,
                            UserId = "2"
                        },
                        new
                        {
                            Id = 5,
                            Age = 33,
                            AvatarUrl = "https://img.freepik.com/psd-gratuitas/ilustracao-3d-de-avatar-ou-perfil-humano_23-2150671122.jpg",
                            BirthAt = new DateTime(2024, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthCityId = 1,
                            CurrentLocationId = 1,
                            FirstName = "Charlie",
                            Gender = "M",
                            LastName = "Brown",
                            Money = 0m,
                            UserId = "2"
                        },
                        new
                        {
                            Id = 6,
                            Age = 35,
                            AvatarUrl = "https://img.freepik.com/psd-gratuitas/ilustracao-3d-de-avatar-ou-perfil-humano_23-2150671122.jpg",
                            BirthAt = new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthCityId = 1,
                            CurrentLocationId = 1,
                            FirstName = "Dave",
                            Gender = "M",
                            LastName = "Wilson",
                            Money = 0m,
                            UserId = "2"
                        },
                        new
                        {
                            Id = 7,
                            Age = 21,
                            AvatarUrl = "https://img.freepik.com/psd-gratuitas/ilustracao-3d-de-avatar-ou-perfil-humano_23-2150671122.jpg",
                            BirthAt = new DateTime(2024, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthCityId = 1,
                            CurrentLocationId = 1,
                            FirstName = "Emily",
                            Gender = "F",
                            LastName = "Davis",
                            Money = 0m,
                            UserId = "3"
                        },
                        new
                        {
                            Id = 8,
                            Age = 27,
                            AvatarUrl = "https://img.freepik.com/psd-gratuitas/ilustracao-3d-de-avatar-ou-perfil-humano_23-2150671122.jpg",
                            BirthAt = new DateTime(2024, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthCityId = 1,
                            CurrentLocationId = 1,
                            FirstName = "Frank",
                            Gender = "M",
                            LastName = "Miller",
                            Money = 0m,
                            UserId = "3"
                        },
                        new
                        {
                            Id = 9,
                            Age = 19,
                            AvatarUrl = "https://img.freepik.com/psd-gratuitas/ilustracao-3d-de-avatar-ou-perfil-humano_23-2150671122.jpg",
                            BirthAt = new DateTime(2024, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthCityId = 1,
                            CurrentLocationId = 1,
                            FirstName = "Grace",
                            Gender = "F",
                            LastName = "Lee",
                            Money = 0m,
                            UserId = "3"
                        },
                        new
                        {
                            Id = 10,
                            Age = 23,
                            AvatarUrl = "https://img.freepik.com/psd-gratuitas/ilustracao-3d-de-avatar-ou-perfil-humano_23-2150671122.jpg",
                            BirthAt = new DateTime(2024, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthCityId = 1,
                            CurrentLocationId = 1,
                            FirstName = "Hank",
                            Gender = "M",
                            LastName = "Taylor",
                            Money = 0m,
                            UserId = "4"
                        },
                        new
                        {
                            Id = 11,
                            Age = 26,
                            AvatarUrl = "https://img.freepik.com/psd-gratuitas/ilustracao-3d-de-avatar-ou-perfil-humano_23-2150671122.jpg",
                            BirthAt = new DateTime(2024, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthCityId = 1,
                            CurrentLocationId = 1,
                            FirstName = "Ivy",
                            Gender = "F",
                            LastName = "White",
                            Money = 0m,
                            UserId = "4"
                        },
                        new
                        {
                            Id = 12,
                            Age = 32,
                            AvatarUrl = "https://img.freepik.com/psd-gratuitas/ilustracao-3d-de-avatar-ou-perfil-humano_23-2150671122.jpg",
                            BirthAt = new DateTime(2024, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthCityId = 1,
                            CurrentLocationId = 1,
                            FirstName = "Jack",
                            Gender = "M",
                            LastName = "Black",
                            Money = 0m,
                            UserId = "4"
                        });
                });

            modelBuilder.Entity("PopFake.Models.CharacterAtributte", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("AtributteId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.HasKey("CharacterId", "AtributteId");

                    b.HasIndex("AtributteId");

                    b.ToTable("CharacterAtributtes");
                });

            modelBuilder.Entity("PopFake.Models.CharacterSkill", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("SkillId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.HasKey("CharacterId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("CharacterSkills");
                });

            modelBuilder.Entity("PopFake.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rio de Janeiro",
                            Timezone = "America/Sao_Paulo"
                        });
                });

            modelBuilder.Entity("PopFake.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<int>("CompanyType")
                        .HasColumnType("integer");

                    b.Property<decimal>("Money")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            CompanyType = 0,
                            Money = 1000000000m,
                            Name = "Prefeitura do Rio de Janeiro"
                        });
                });

            modelBuilder.Entity("PopFake.Models.CompanyShareholder", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsPresident")
                        .HasColumnType("boolean");

                    b.Property<int>("Shares")
                        .HasColumnType("integer");

                    b.HasKey("CharacterId", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyShareholders");
                });

            modelBuilder.Entity("PopFake.Models.ExampleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Examples");
                });

            modelBuilder.Entity("PopFake.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Money")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quality")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            CompanyId = 1,
                            Money = 1000000m,
                            Name = "Praia de Copacabana",
                            Quality = 5,
                            Type = 0,
                            TypeId = 0
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            CompanyId = 1,
                            Money = 1000000m,
                            Name = "Parque do Flamengo",
                            Quality = 5,
                            Type = 0,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            CityId = 1,
                            CompanyId = 1,
                            Money = 1000000m,
                            Name = "Parque Olímpico",
                            Quality = 5,
                            Type = 0,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 4,
                            CityId = 1,
                            CompanyId = 1,
                            Money = 1000000m,
                            Name = "Academia de Ginástica",
                            Quality = 5,
                            Type = 0,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 5,
                            CityId = 1,
                            CompanyId = 1,
                            Money = 1000000m,
                            Name = "Hotel Copacabana Palace",
                            Quality = 5,
                            Type = 0,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 6,
                            CityId = 1,
                            CompanyId = 1,
                            Money = 1000000m,
                            Name = "Restaurante Fasano",
                            Quality = 5,
                            Type = 0,
                            TypeId = 5
                        },
                        new
                        {
                            Id = 7,
                            CityId = 1,
                            CompanyId = 1,
                            Money = 1000000m,
                            Name = "Loja de Artigos Esportivos",
                            Quality = 5,
                            Type = 0,
                            TypeId = 6
                        },
                        new
                        {
                            Id = 8,
                            CityId = 1,
                            CompanyId = 1,
                            Money = 1000000m,
                            Name = "Centro de Treinamento",
                            Quality = 5,
                            Type = 0,
                            TypeId = 7
                        });
                });

            modelBuilder.Entity("PopFake.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("PopFake.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<DateTime>("TokenCreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("TokenExpiredAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "80c9b350-192b-4d8f-89df-d8872ceed18f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d373c217-dcc3-4968-9b40-d3b8b2b326fb",
                            DataNascimento = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user1@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nickname = "User 1",
                            NormalizedEmail = "USER1@EXAMPLE.COM",
                            NormalizedUserName = "USER1",
                            PasswordHash = "AQAAAAIAAYagAAAAECN+bXyOXSplMSAaxxyILAVWl9k1tY6WfupqK0eodtGRGosh13s6i1qSfN7X5s9+bg==",
                            PhoneNumberConfirmed = false,
                            RefreshToken = "",
                            RegisteredAt = new DateTime(2024, 10, 21, 21, 49, 43, 621, DateTimeKind.Local).AddTicks(9299),
                            SecurityStamp = "",
                            TokenCreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpiredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false,
                            UserName = "user1"
                        },
                        new
                        {
                            Id = "e06d6e84-822a-4485-a517-2754d05e2759",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "218e3181-bde4-406c-8d71-e02631e9f31e",
                            DataNascimento = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user2@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nickname = "User 2",
                            NormalizedEmail = "USER2@EXAMPLE.COM",
                            NormalizedUserName = "USER2",
                            PasswordHash = "AQAAAAIAAYagAAAAEH2F/v3utaSxUTIUsiFDSRSqFJMe4m/HQ5/j8GxN98EQLHnM4zYejoy352OTVoVbFw==",
                            PhoneNumberConfirmed = false,
                            RefreshToken = "",
                            RegisteredAt = new DateTime(2024, 10, 21, 21, 49, 43, 697, DateTimeKind.Local).AddTicks(4823),
                            SecurityStamp = "",
                            TokenCreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpiredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false,
                            UserName = "user2"
                        },
                        new
                        {
                            Id = "ad666ca1-ff2b-4d09-a167-406b14da431f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "04752f34-bf88-4c31-9ad8-e490add2a11f",
                            DataNascimento = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user3@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nickname = "User 3",
                            NormalizedEmail = "USER3@EXAMPLE.COM",
                            NormalizedUserName = "USER3",
                            PasswordHash = "AQAAAAIAAYagAAAAEIGktG+zI+U4nmI7MRVm5pjCzVfhBT9+3JAAx5DTTqbUwzD/MCT36TaXcjbneBqilg==",
                            PhoneNumberConfirmed = false,
                            RefreshToken = "",
                            RegisteredAt = new DateTime(2024, 10, 21, 21, 49, 43, 762, DateTimeKind.Local).AddTicks(5978),
                            SecurityStamp = "",
                            TokenCreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpiredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false,
                            UserName = "user3"
                        },
                        new
                        {
                            Id = "d49e3a77-6b79-4a0b-9360-d3420a5750f7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1402803d-107f-4d53-9b0e-8cdaa72e3bc4",
                            DataNascimento = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user4@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nickname = "User 4",
                            NormalizedEmail = "USER4@EXAMPLE.COM",
                            NormalizedUserName = "USER4",
                            PasswordHash = "AQAAAAIAAYagAAAAEMf4+rHGZ4g/c8oJSXjH/VI1CbIYwXTFuIkF/nvcqY9twGLR9qaaAfvdIfsmAObvqQ==",
                            PhoneNumberConfirmed = false,
                            RefreshToken = "",
                            RegisteredAt = new DateTime(2024, 10, 21, 21, 49, 43, 839, DateTimeKind.Local).AddTicks(220),
                            SecurityStamp = "",
                            TokenCreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpiredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false,
                            UserName = "user4"
                        },
                        new
                        {
                            Id = "3edce9ce-8819-4ec9-a68d-dd6925ad90f5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5aee532f-6452-40dd-bba8-29667d8130e2",
                            DataNascimento = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user5@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nickname = "User 5",
                            NormalizedEmail = "USER5@EXAMPLE.COM",
                            NormalizedUserName = "USER5",
                            PasswordHash = "AQAAAAIAAYagAAAAEAKTND3rdbUBX3uvboSe/Bc8t1fXHxSQIeMrhsmFiS+0eV34oBapVSE9Hvsrr9rL3w==",
                            PhoneNumberConfirmed = false,
                            RefreshToken = "",
                            RegisteredAt = new DateTime(2024, 10, 21, 21, 49, 43, 935, DateTimeKind.Local).AddTicks(4217),
                            SecurityStamp = "",
                            TokenCreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpiredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false,
                            UserName = "user5"
                        },
                        new
                        {
                            Id = "0730545a-e730-42d1-ad38-af79d72e726c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2098a207-e9e5-4b58-b6e9-0b0d1c2d6438",
                            DataNascimento = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user6@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nickname = "User 6",
                            NormalizedEmail = "USER6@EXAMPLE.COM",
                            NormalizedUserName = "USER6",
                            PasswordHash = "AQAAAAIAAYagAAAAEEEdrYBcIwEJwSTdRrxwwE/G+sqIXaZonxjRLqPHLTxO3IkrZazGxFg6EtRYBfIpBQ==",
                            PhoneNumberConfirmed = false,
                            RefreshToken = "",
                            RegisteredAt = new DateTime(2024, 10, 21, 21, 49, 44, 0, DateTimeKind.Local).AddTicks(7845),
                            SecurityStamp = "",
                            TokenCreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpiredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false,
                            UserName = "user6"
                        },
                        new
                        {
                            Id = "bcd4ac43-2f0d-40aa-a084-8b02172e598b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "18139850-c3a3-4c75-b1d6-365975fee013",
                            DataNascimento = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user7@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nickname = "User 7",
                            NormalizedEmail = "USER7@EXAMPLE.COM",
                            NormalizedUserName = "USER7",
                            PasswordHash = "AQAAAAIAAYagAAAAEF69SBiGjILBDbFrBZSWaGW5yrzm9uXO1fvDK/GOC6OPVDW0enMcDlNlNJIZlAx2XQ==",
                            PhoneNumberConfirmed = false,
                            RefreshToken = "",
                            RegisteredAt = new DateTime(2024, 10, 21, 21, 49, 44, 88, DateTimeKind.Local).AddTicks(8500),
                            SecurityStamp = "",
                            TokenCreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpiredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false,
                            UserName = "user7"
                        },
                        new
                        {
                            Id = "ac7dcb36-96e4-4f2e-9187-936fae618a8b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "03ee45a6-64ce-434f-a3b9-38f8c3b1b913",
                            DataNascimento = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user8@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nickname = "User 8",
                            NormalizedEmail = "USER8@EXAMPLE.COM",
                            NormalizedUserName = "USER8",
                            PasswordHash = "AQAAAAIAAYagAAAAEKjnIPB2od4czxnagoVeFau4HJf96NvsHr9E+aO9QjUqSJoPyugo8ClzMyF0f1Vzqg==",
                            PhoneNumberConfirmed = false,
                            RefreshToken = "",
                            RegisteredAt = new DateTime(2024, 10, 21, 21, 49, 44, 157, DateTimeKind.Local).AddTicks(1735),
                            SecurityStamp = "",
                            TokenCreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpiredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false,
                            UserName = "user8"
                        },
                        new
                        {
                            Id = "91c266f1-be7b-4f7a-86b8-d005a0fd3694",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f9209ad5-6fa4-45e6-b122-76e697d010e6",
                            DataNascimento = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user9@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nickname = "User 9",
                            NormalizedEmail = "USER9@EXAMPLE.COM",
                            NormalizedUserName = "USER9",
                            PasswordHash = "AQAAAAIAAYagAAAAELlN5hU+DCpI/SaJZfaHyhM4AWHLDjRGYeVHu4VHGDvKkqlyaOmpQTwQ0TnSO8NyCA==",
                            PhoneNumberConfirmed = false,
                            RefreshToken = "",
                            RegisteredAt = new DateTime(2024, 10, 21, 21, 49, 44, 232, DateTimeKind.Local).AddTicks(366),
                            SecurityStamp = "",
                            TokenCreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpiredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false,
                            UserName = "user9"
                        },
                        new
                        {
                            Id = "dba541a5-0093-4e75-b566-4bb623bf48c0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5aacd5dd-d972-4918-9a57-8bd332eb0add",
                            DataNascimento = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user10@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nickname = "User 10",
                            NormalizedEmail = "USER10@EXAMPLE.COM",
                            NormalizedUserName = "USER10",
                            PasswordHash = "AQAAAAIAAYagAAAAEEMwBK2I6SCMFK4m/7sBYbbKLbD14N4iG2n/nXmLWWh745ZPFgLH1D6CDZLXJg/2aw==",
                            PhoneNumberConfirmed = false,
                            RefreshToken = "",
                            RegisteredAt = new DateTime(2024, 10, 21, 21, 49, 44, 291, DateTimeKind.Local).AddTicks(8121),
                            SecurityStamp = "",
                            TokenCreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpiredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false,
                            UserName = "user10"
                        },
                        new
                        {
                            Id = "ab093ee2-c1fb-4114-9e57-0445d7e54055",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8041cd95-16b1-4a17-8dd7-43e0c477e1f6",
                            DataNascimento = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user11@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nickname = "User 11",
                            NormalizedEmail = "USER11@EXAMPLE.COM",
                            NormalizedUserName = "USER11",
                            PasswordHash = "AQAAAAIAAYagAAAAECl4fOnuslA556nhVcWPBdWTUoVRjaHQ7rVAQ4+leg94iKexaXoBd+6G3xNL7M0Uug==",
                            PhoneNumberConfirmed = false,
                            RefreshToken = "",
                            RegisteredAt = new DateTime(2024, 10, 21, 21, 49, 44, 352, DateTimeKind.Local).AddTicks(8471),
                            SecurityStamp = "",
                            TokenCreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpiredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false,
                            UserName = "user11"
                        },
                        new
                        {
                            Id = "e087eaa7-483b-4778-bde7-461ee495b049",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2ae029b4-420a-4bb0-8293-62fcd6365fab",
                            DataNascimento = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user12@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nickname = "User 12",
                            NormalizedEmail = "USER12@EXAMPLE.COM",
                            NormalizedUserName = "USER12",
                            PasswordHash = "AQAAAAIAAYagAAAAEHBN3qmgP1V7iLPsF/hU5Iw9OX4YbttkTvpSUVhu45hmLwxgLHDLT0cZdK1WeKwLkg==",
                            PhoneNumberConfirmed = false,
                            RefreshToken = "",
                            RegisteredAt = new DateTime(2024, 10, 21, 21, 49, 44, 411, DateTimeKind.Local).AddTicks(7072),
                            SecurityStamp = "",
                            TokenCreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpiredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false,
                            UserName = "user12"
                        },
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1980bd2b-e1b9-4555-b5b6-2b4074f21dfb",
                            DataNascimento = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "userunique1@email.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nickname = "User One",
                            NormalizedEmail = "USERUNIQUE1@EMAIL.COM",
                            NormalizedUserName = "USERUNIQUE1",
                            PasswordHash = "AQAAAAIAAYagAAAAEEUVhMCZcOgAwsxclOMefETpHOKz3CBDwpOKYy0jvznPxl9k7zr0ic+LIu1pvw8hkg==",
                            PhoneNumberConfirmed = false,
                            RefreshToken = "",
                            RegisteredAt = new DateTime(2024, 10, 21, 21, 49, 44, 469, DateTimeKind.Local).AddTicks(1658),
                            SecurityStamp = "",
                            TokenCreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpiredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false,
                            UserName = "userunique1"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2ef545f9-bc87-4fc4-94e5-00ea0f37bd19",
                            DataNascimento = new DateTime(1985, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "userunique2@email.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nickname = "User Two",
                            NormalizedEmail = "USERUNIQUE2@EMAIL.COM",
                            NormalizedUserName = "USERUNIQUE2",
                            PasswordHash = "AQAAAAIAAYagAAAAEGpeq1rP4xLxOIQq7pn3V5VAMY3S0uOUdM5TNAwt5AWr41UnuyrLp/8tPFMOskMKFA==",
                            PhoneNumberConfirmed = false,
                            RefreshToken = "",
                            RegisteredAt = new DateTime(2024, 10, 21, 21, 49, 44, 530, DateTimeKind.Local).AddTicks(5633),
                            SecurityStamp = "",
                            TokenCreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpiredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false,
                            UserName = "userunique2"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "be526ec7-ec64-48a5-a150-9d81f4867ba4",
                            DataNascimento = new DateTime(1990, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "userunique3@email.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nickname = "User Three",
                            NormalizedEmail = "USERUNIQUE3@EMAIL.COM",
                            NormalizedUserName = "USERUNIQUE3",
                            PasswordHash = "AQAAAAIAAYagAAAAEOItBhJsQkVIutGIacldf4eNbwYJqr7N7NBDY3e79cQ5PMSoKNVKyjIFSN62/MR6lQ==",
                            PhoneNumberConfirmed = false,
                            RefreshToken = "",
                            RegisteredAt = new DateTime(2024, 10, 21, 21, 49, 44, 586, DateTimeKind.Local).AddTicks(8833),
                            SecurityStamp = "",
                            TokenCreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpiredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false,
                            UserName = "userunique3"
                        },
                        new
                        {
                            Id = "4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9fe056fd-a0f6-4b70-9708-2430c00e009d",
                            DataNascimento = new DateTime(1995, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "userunique4@email.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nickname = "User Four",
                            NormalizedEmail = "USERUNIQUE4@EMAIL.COM",
                            NormalizedUserName = "USERUNIQUE4",
                            PasswordHash = "AQAAAAIAAYagAAAAEKvTyj3QXeGGCPR1VgqHuDcGUycvmUS9yFywa72RIpo1QVy6wnyeQ9LMvd9E6fsaSg==",
                            PhoneNumberConfirmed = false,
                            RefreshToken = "",
                            RegisteredAt = new DateTime(2024, 10, 21, 21, 49, 44, 646, DateTimeKind.Local).AddTicks(3448),
                            SecurityStamp = "",
                            TokenCreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpiredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false,
                            UserName = "userunique4"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PopFake.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PopFake.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PopFake.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PopFake.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PopFake.Models.Character", b =>
                {
                    b.HasOne("PopFake.Models.City", "BirthCity")
                        .WithMany("Characters")
                        .HasForeignKey("BirthCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PopFake.Models.Location", "CurrentLocation")
                        .WithMany("Characters")
                        .HasForeignKey("CurrentLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PopFake.Models.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BirthCity");

                    b.Navigation("CurrentLocation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PopFake.Models.CharacterAtributte", b =>
                {
                    b.HasOne("PopFake.Models.Atributte", "Atributte")
                        .WithMany("CharacterAtributtes")
                        .HasForeignKey("AtributteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PopFake.Models.Character", "Character")
                        .WithMany("CharacterAtributtes")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atributte");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("PopFake.Models.CharacterSkill", b =>
                {
                    b.HasOne("PopFake.Models.Character", "Character")
                        .WithMany("CharacterSkills")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PopFake.Models.Skill", "Skill")
                        .WithMany("CharacterSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("PopFake.Models.Company", b =>
                {
                    b.HasOne("PopFake.Models.City", "City")
                        .WithMany("Companies")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("PopFake.Models.CompanyShareholder", b =>
                {
                    b.HasOne("PopFake.Models.Character", "Character")
                        .WithMany("CompanyShareholders")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PopFake.Models.Company", "Company")
                        .WithMany("CompanyShareholders")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("PopFake.Models.Location", b =>
                {
                    b.HasOne("PopFake.Models.City", "City")
                        .WithMany("Locations")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PopFake.Models.Company", "Company")
                        .WithMany("Locations")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("PopFake.Models.Atributte", b =>
                {
                    b.Navigation("CharacterAtributtes");
                });

            modelBuilder.Entity("PopFake.Models.Character", b =>
                {
                    b.Navigation("CharacterAtributtes");

                    b.Navigation("CharacterSkills");

                    b.Navigation("CompanyShareholders");
                });

            modelBuilder.Entity("PopFake.Models.City", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Companies");

                    b.Navigation("Locations");
                });

            modelBuilder.Entity("PopFake.Models.Company", b =>
                {
                    b.Navigation("CompanyShareholders");

                    b.Navigation("Locations");
                });

            modelBuilder.Entity("PopFake.Models.Location", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("PopFake.Models.Skill", b =>
                {
                    b.Navigation("CharacterSkills");
                });

            modelBuilder.Entity("PopFake.Models.User", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
